version: 2.1
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

executors: 
  docker-node-executor:
    docker:
      - image: cimg/node:lts
jobs:
  test-commit:
    executor: docker-node-executor
    parallelism: 5
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "95:de:a0:5f:08:72:e0:f4:d7:a8:86:c7:64:a6:11:a0"
      - run: mkdir ~/junit
      - run:
          name: rum test
          command: |
            node -v
            npm install
            TEST=$(circleci tests glob "./__tests__/*.js" | circleci tests split --split-by=timings)
            npm run test $TEST
      - run:
          command: cp ./coverage/clover.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
workflows:
  main:
    jobs:
      - test-commit:
          filters: *on-push-main

          