version: 2.1
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

executors: 
  docker-node-executor:
    docker:
      - image: cimg/node:lts
jobs:
  test-commit:
    executor: docker-node-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "95:de:a0:5f:08:72:e0:f4:d7:a8:86:c7:64:a6:11:a0"
      - run:
          name: rum test
          command: |
            node -v
            npm install
            npm run test
workflows:
  main:
    jobs:
      - test-commit:
          filters: *on-push-main

          